// default package
// Generated 09/12/2019 15:01:45 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cartao generated by hbm2java
 */
public class Cartao implements java.io.Serializable {

	private String codigo;
	private String nome;
	private Date validade;
	private Set<Cliente> clientes = new HashSet<Cliente>(0);

	public Cartao() {
	}

	public Cartao(String codigo) {
		this.codigo = codigo;
	}

	public Cartao(String codigo, String nome, Date validade, Set<Cliente> clientes) {
		this.codigo = codigo;
		this.nome = nome;
		this.validade = validade;
		this.clientes = clientes;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Date getValidade() {
		return this.validade;
	}

	public void setValidade(Date validade) {
		this.validade = validade;
	}

	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

}
