// default package
// Generated 09/12/2019 15:01:45 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private String cpf;
	private Cartao cartao;
	private Endereco endereco;
	private String nome;
	private String telefone;
	private Set<LivroRetirado> livroRetirados = new HashSet<LivroRetirado>(0);

	public Cliente() {
	}

	public Cliente(String cpf) {
		this.cpf = cpf;
	}

	public Cliente(String cpf, Cartao cartao, Endereco endereco, String nome, String telefone,
			Set<LivroRetirado> livroRetirados) {
		this.cpf = cpf;
		this.cartao = cartao;
		this.endereco = endereco;
		this.nome = nome;
		this.telefone = telefone;
		this.livroRetirados = livroRetirados;
	}

	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	public Cartao getCartao() {
		return this.cartao;
	}

	public void setCartao(Cartao cartao) {
		this.cartao = cartao;
	}

	public Endereco getEndereco() {
		return this.endereco;
	}

	public void setEndereco(Endereco endereco) {
		this.endereco = endereco;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	public Set<LivroRetirado> getLivroRetirados() {
		return this.livroRetirados;
	}

	public void setLivroRetirados(Set<LivroRetirado> livroRetirados) {
		this.livroRetirados = livroRetirados;
	}

}
