// default package
// Generated 09/12/2019 15:01:45 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Estante generated by hbm2java
 */
public class Estante implements java.io.Serializable {

	private int estanteId;
	private Biblioteca biblioteca;
	private Set<Prateleira> prateleiras = new HashSet<Prateleira>(0);

	public Estante() {
	}

	public Estante(int estanteId, Biblioteca biblioteca) {
		this.estanteId = estanteId;
		this.biblioteca = biblioteca;
	}

	public Estante(int estanteId, Biblioteca biblioteca, Set<Prateleira> prateleiras) {
		this.estanteId = estanteId;
		this.biblioteca = biblioteca;
		this.prateleiras = prateleiras;
	}

	public int getEstanteId() {
		return this.estanteId;
	}

	public void setEstanteId(int estanteId) {
		this.estanteId = estanteId;
	}

	public Biblioteca getBiblioteca() {
		return this.biblioteca;
	}

	public void setBiblioteca(Biblioteca biblioteca) {
		this.biblioteca = biblioteca;
	}

	public Set<Prateleira> getPrateleiras() {
		return this.prateleiras;
	}

	public void setPrateleiras(Set<Prateleira> prateleiras) {
		this.prateleiras = prateleiras;
	}

}
