// default package
// Generated 09/12/2019 15:01:45 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Evento generated by hbm2java
 */
public class Evento implements java.io.Serializable {

	private int eventoId;
	private LivroRetirado livroRetirado;
	private Integer tipoEvento;
	private Date data;
	private Set<LivroRetirado> livroRetiradosForEventoDevolucaoId = new HashSet<LivroRetirado>(0);
	private Set<LivroRetirado> livroRetiradosForEventoRetiradaId = new HashSet<LivroRetirado>(0);

	public Evento() {
	}

	public Evento(int eventoId) {
		this.eventoId = eventoId;
	}

	public Evento(int eventoId, LivroRetirado livroRetirado, Integer tipoEvento, Date data,
			Set<LivroRetirado> livroRetiradosForEventoDevolucaoId,
			Set<LivroRetirado> livroRetiradosForEventoRetiradaId) {
		this.eventoId = eventoId;
		this.livroRetirado = livroRetirado;
		this.tipoEvento = tipoEvento;
		this.data = data;
		this.livroRetiradosForEventoDevolucaoId = livroRetiradosForEventoDevolucaoId;
		this.livroRetiradosForEventoRetiradaId = livroRetiradosForEventoRetiradaId;
	}

	public int getEventoId() {
		return this.eventoId;
	}

	public void setEventoId(int eventoId) {
		this.eventoId = eventoId;
	}

	public LivroRetirado getLivroRetirado() {
		return this.livroRetirado;
	}

	public void setLivroRetirado(LivroRetirado livroRetirado) {
		this.livroRetirado = livroRetirado;
	}

	public Integer getTipoEvento() {
		return this.tipoEvento;
	}

	public void setTipoEvento(Integer tipoEvento) {
		this.tipoEvento = tipoEvento;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public Set<LivroRetirado> getLivroRetiradosForEventoDevolucaoId() {
		return this.livroRetiradosForEventoDevolucaoId;
	}

	public void setLivroRetiradosForEventoDevolucaoId(Set<LivroRetirado> livroRetiradosForEventoDevolucaoId) {
		this.livroRetiradosForEventoDevolucaoId = livroRetiradosForEventoDevolucaoId;
	}

	public Set<LivroRetirado> getLivroRetiradosForEventoRetiradaId() {
		return this.livroRetiradosForEventoRetiradaId;
	}

	public void setLivroRetiradosForEventoRetiradaId(Set<LivroRetirado> livroRetiradosForEventoRetiradaId) {
		this.livroRetiradosForEventoRetiradaId = livroRetiradosForEventoRetiradaId;
	}

}
