// default package
// Generated 26/11/2019 13:42:20 by Hibernate Tools 3.6.0.Final

import java.util.Date;

/**
 * Evento generated by hbm2java
 */
public class Evento implements java.io.Serializable {

	private int eventoId;
	private LivroRetirado livroRetirado;
	private int tipoEventoId;
	private Date dataEvento;

	public Evento() {
	}

	public Evento(int eventoId, LivroRetirado livroRetirado, int tipoEventoId, Date dataEvento) {
		this.eventoId = eventoId;
		this.livroRetirado = livroRetirado;
		this.tipoEventoId = tipoEventoId;
		this.dataEvento = dataEvento;
	}

	public int getEventoId() {
		return this.eventoId;
	}

	public void setEventoId(int eventoId) {
		this.eventoId = eventoId;
	}

	public LivroRetirado getLivroRetirado() {
		return this.livroRetirado;
	}

	public void setLivroRetirado(LivroRetirado livroRetirado) {
		this.livroRetirado = livroRetirado;
	}

	public int getTipoEventoId() {
		return this.tipoEventoId;
	}

	public void setTipoEventoId(int tipoEventoId) {
		this.tipoEventoId = tipoEventoId;
	}

	public Date getDataEvento() {
		return this.dataEvento;
	}

	public void setDataEvento(Date dataEvento) {
		this.dataEvento = dataEvento;
	}

}
