// default package
// Generated 26/11/2019 13:42:20 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LivroRetirado generated by hbm2java
 */
public class LivroRetirado implements java.io.Serializable {

	private int livroRetiradoId;
	private Livro livro;
	private Cartao cartao;
	private Date dataDevolucao;
	private Set<Evento> eventos = new HashSet<Evento>(0);

	public LivroRetirado() {
	}

	public LivroRetirado(int livroRetiradoId, Livro livro, Cartao cartao, Date dataDevolucao) {
		this.livroRetiradoId = livroRetiradoId;
		this.livro = livro;
		this.cartao = cartao;
		this.dataDevolucao = dataDevolucao;
	}

	public LivroRetirado(int livroRetiradoId, Livro livro, Cartao cartao, Date dataDevolucao, Set<Evento> eventos) {
		this.livroRetiradoId = livroRetiradoId;
		this.livro = livro;
		this.cartao = cartao;
		this.dataDevolucao = dataDevolucao;
		this.eventos = eventos;
	}

	public int getLivroRetiradoId() {
		return this.livroRetiradoId;
	}

	public void setLivroRetiradoId(int livroRetiradoId) {
		this.livroRetiradoId = livroRetiradoId;
	}

	public Livro getLivro() {
		return this.livro;
	}

	public void setLivro(Livro livro) {
		this.livro = livro;
	}

	public Cartao getCartao() {
		return this.cartao;
	}

	public void setCartao(Cartao cartao) {
		this.cartao = cartao;
	}

	public Date getDataDevolucao() {
		return this.dataDevolucao;
	}

	public void setDataDevolucao(Date dataDevolucao) {
		this.dataDevolucao = dataDevolucao;
	}

	public Set<Evento> getEventos() {
		return this.eventos;
	}

	public void setEventos(Set<Evento> eventos) {
		this.eventos = eventos;
	}

}
