// default package
// Generated 09/12/2019 15:01:45 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LivroRetirado generated by hbm2java
 */
public class LivroRetirado implements java.io.Serializable {

	private int livroRetiradoId;
	private Evento eventoByEventoRetiradaId;
	private Livro livro;
	private Cliente cliente;
	private Evento eventoByEventoDevolucaoId;
	private Date dataDevolucao;
	private Set<Evento> eventos = new HashSet<Evento>(0);

	public LivroRetirado() {
	}

	public LivroRetirado(int livroRetiradoId, Evento eventoByEventoRetiradaId, Livro livro, Cliente cliente,
			Date dataDevolucao) {
		this.livroRetiradoId = livroRetiradoId;
		this.eventoByEventoRetiradaId = eventoByEventoRetiradaId;
		this.livro = livro;
		this.cliente = cliente;
		this.dataDevolucao = dataDevolucao;
	}

	public LivroRetirado(int livroRetiradoId, Evento eventoByEventoRetiradaId, Livro livro, Cliente cliente,
			Evento eventoByEventoDevolucaoId, Date dataDevolucao, Set<Evento> eventos) {
		this.livroRetiradoId = livroRetiradoId;
		this.eventoByEventoRetiradaId = eventoByEventoRetiradaId;
		this.livro = livro;
		this.cliente = cliente;
		this.eventoByEventoDevolucaoId = eventoByEventoDevolucaoId;
		this.dataDevolucao = dataDevolucao;
		this.eventos = eventos;
	}

	public int getLivroRetiradoId() {
		return this.livroRetiradoId;
	}

	public void setLivroRetiradoId(int livroRetiradoId) {
		this.livroRetiradoId = livroRetiradoId;
	}

	public Evento getEventoByEventoRetiradaId() {
		return this.eventoByEventoRetiradaId;
	}

	public void setEventoByEventoRetiradaId(Evento eventoByEventoRetiradaId) {
		this.eventoByEventoRetiradaId = eventoByEventoRetiradaId;
	}

	public Livro getLivro() {
		return this.livro;
	}

	public void setLivro(Livro livro) {
		this.livro = livro;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Evento getEventoByEventoDevolucaoId() {
		return this.eventoByEventoDevolucaoId;
	}

	public void setEventoByEventoDevolucaoId(Evento eventoByEventoDevolucaoId) {
		this.eventoByEventoDevolucaoId = eventoByEventoDevolucaoId;
	}

	public Date getDataDevolucao() {
		return this.dataDevolucao;
	}

	public void setDataDevolucao(Date dataDevolucao) {
		this.dataDevolucao = dataDevolucao;
	}

	public Set<Evento> getEventos() {
		return this.eventos;
	}

	public void setEventos(Set<Evento> eventos) {
		this.eventos = eventos;
	}

}
