// default package
// Generated 28/11/2019 14:49:05 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Livro generated by hbm2java
 */
public class Livro implements java.io.Serializable {

	private int livroId;
	private Prateleira prateleira;
	private String isbn;
	private String autor;
	private String titulo;
	private String editora;
	private int edicao;
	private int numeropaginas;
	private boolean retirado;
	private Set<LivroRetirado> livroRetirados = new HashSet<LivroRetirado>(0);

	public Livro() {
	}

	public Livro(int livroId, Prateleira prateleira, String isbn, String autor, String titulo, String editora,
			int edicao, int numeropaginas, boolean retirado) {
		this.livroId = livroId;
		this.prateleira = prateleira;
		this.isbn = isbn;
		this.autor = autor;
		this.titulo = titulo;
		this.editora = editora;
		this.edicao = edicao;
		this.numeropaginas = numeropaginas;
		this.retirado = retirado;
	}

	public Livro(int livroId, Prateleira prateleira, String isbn, String autor, String titulo, String editora,
			int edicao, int numeropaginas, boolean retirado, Set<LivroRetirado> livroRetirados) {
		this.livroId = livroId;
		this.prateleira = prateleira;
		this.isbn = isbn;
		this.autor = autor;
		this.titulo = titulo;
		this.editora = editora;
		this.edicao = edicao;
		this.numeropaginas = numeropaginas;
		this.retirado = retirado;
		this.livroRetirados = livroRetirados;
	}

	public int getLivroId() {
		return this.livroId;
	}

	public void setLivroId(int livroId) {
		this.livroId = livroId;
	}

	public Prateleira getPrateleira() {
		return this.prateleira;
	}

	public void setPrateleira(Prateleira prateleira) {
		this.prateleira = prateleira;
	}

	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public String getAutor() {
		return this.autor;
	}

	public void setAutor(String autor) {
		this.autor = autor;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getEditora() {
		return this.editora;
	}

	public void setEditora(String editora) {
		this.editora = editora;
	}

	public int getEdicao() {
		return this.edicao;
	}

	public void setEdicao(int edicao) {
		this.edicao = edicao;
	}

	public int getNumeropaginas() {
		return this.numeropaginas;
	}

	public void setNumeropaginas(int numeropaginas) {
		this.numeropaginas = numeropaginas;
	}

	public boolean isRetirado() {
		return this.retirado;
	}

	public void setRetirado(boolean retirado) {
		this.retirado = retirado;
	}

	public Set<LivroRetirado> getLivroRetirados() {
		return this.livroRetirados;
	}

	public void setLivroRetirados(Set<LivroRetirado> livroRetirados) {
		this.livroRetirados = livroRetirados;
	}

}
