// default package
// Generated 09/12/2019 15:01:45 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Livro generated by hbm2java
 */
public class Livro implements java.io.Serializable {

	private int livroId;
	private Prateleira prateleira;
	private String isbn;
	private String titulo;
	private String autor;
	private String editora;
	private Integer edicao;
	private Integer numeropaginas;
	private Boolean retirado;
	private Set<LivroRetirado> livroRetirados = new HashSet<LivroRetirado>(0);

	public Livro() {
	}

	public Livro(int livroId, Prateleira prateleira) {
		this.livroId = livroId;
		this.prateleira = prateleira;
	}

	public Livro(int livroId, Prateleira prateleira, String isbn, String titulo, String autor, String editora,
			Integer edicao, Integer numeropaginas, Boolean retirado, Set<LivroRetirado> livroRetirados) {
		this.livroId = livroId;
		this.prateleira = prateleira;
		this.isbn = isbn;
		this.titulo = titulo;
		this.autor = autor;
		this.editora = editora;
		this.edicao = edicao;
		this.numeropaginas = numeropaginas;
		this.retirado = retirado;
		this.livroRetirados = livroRetirados;
	}

	public int getLivroId() {
		return this.livroId;
	}

	public void setLivroId(int livroId) {
		this.livroId = livroId;
	}

	public Prateleira getPrateleira() {
		return this.prateleira;
	}

	public void setPrateleira(Prateleira prateleira) {
		this.prateleira = prateleira;
	}

	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getAutor() {
		return this.autor;
	}

	public void setAutor(String autor) {
		this.autor = autor;
	}

	public String getEditora() {
		return this.editora;
	}

	public void setEditora(String editora) {
		this.editora = editora;
	}

	public Integer getEdicao() {
		return this.edicao;
	}

	public void setEdicao(Integer edicao) {
		this.edicao = edicao;
	}

	public Integer getNumeropaginas() {
		return this.numeropaginas;
	}

	public void setNumeropaginas(Integer numeropaginas) {
		this.numeropaginas = numeropaginas;
	}

	public Boolean getRetirado() {
		return this.retirado;
	}

	public void setRetirado(Boolean retirado) {
		this.retirado = retirado;
	}

	public Set<LivroRetirado> getLivroRetirados() {
		return this.livroRetirados;
	}

	public void setLivroRetirados(Set<LivroRetirado> livroRetirados) {
		this.livroRetirados = livroRetirados;
	}

}
