// default package
// Generated 26/11/2019 13:42:20 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Prateleira generated by hbm2java
 */
public class Prateleira implements java.io.Serializable {

	private int prateleiraId;
	private Estante estante;
	private Set<Livro> livros = new HashSet<Livro>(0);

	public Prateleira() {
	}

	public Prateleira(int prateleiraId, Estante estante) {
		this.prateleiraId = prateleiraId;
		this.estante = estante;
	}

	public Prateleira(int prateleiraId, Estante estante, Set<Livro> livros) {
		this.prateleiraId = prateleiraId;
		this.estante = estante;
		this.livros = livros;
	}

	public int getPrateleiraId() {
		return this.prateleiraId;
	}

	public void setPrateleiraId(int prateleiraId) {
		this.prateleiraId = prateleiraId;
	}

	public Estante getEstante() {
		return this.estante;
	}

	public void setEstante(Estante estante) {
		this.estante = estante;
	}

	public Set<Livro> getLivros() {
		return this.livros;
	}

	public void setLivros(Set<Livro> livros) {
		this.livros = livros;
	}

}
