// default package
// Generated 26/11/2019 13:42:20 by Hibernate Tools 3.6.0.Final

/**
 * TipoEventoId generated by hbm2java
 */
public class TipoEventoId implements java.io.Serializable {

	private int tipoEventoId;
	private String tipo;
	private String descr;

	public TipoEventoId() {
	}

	public TipoEventoId(int tipoEventoId, String tipo, String descr) {
		this.tipoEventoId = tipoEventoId;
		this.tipo = tipo;
		this.descr = descr;
	}

	public int getTipoEventoId() {
		return this.tipoEventoId;
	}

	public void setTipoEventoId(int tipoEventoId) {
		this.tipoEventoId = tipoEventoId;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TipoEventoId))
			return false;
		TipoEventoId castOther = (TipoEventoId) other;

		return (this.getTipoEventoId() == castOther.getTipoEventoId())
				&& ((this.getTipo() == castOther.getTipo()) || (this.getTipo() != null && castOther.getTipo() != null
						&& this.getTipo().equals(castOther.getTipo())))
				&& ((this.getDescr() == castOther.getDescr()) || (this.getDescr() != null
						&& castOther.getDescr() != null && this.getDescr().equals(castOther.getDescr())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTipoEventoId();
		result = 37 * result + (getTipo() == null ? 0 : this.getTipo().hashCode());
		result = 37 * result + (getDescr() == null ? 0 : this.getDescr().hashCode());
		return result;
	}

}
