// default package
// Generated 26/11/2019 13:42:20 by Hibernate Tools 3.6.0.Final

/**
 * TipoEvento generated by hbm2java
 */
public class TipoEvento implements java.io.Serializable {

	private TipoEventoId id;

	public TipoEvento() {
	}

	public TipoEvento(TipoEventoId id) {
		this.id = id;
	}

	public TipoEventoId getId() {
		return this.id;
	}

	public void setId(TipoEventoId id) {
		this.id = id;
	}

}
